classDiagram

class PresentationLayer {
    +UserController
    +PlaceController
    +ReviewController
    +AmenityController
    +WebServices
    
}

class BusinessLogicLayer {
    +UserManager
    +PlaceManager
    +ReviewManager
    +AmenityManager
}

class PersistenceLayer {
    +UserDAO
    +PlaceDAO
    +ReviewDAO
    +AmenityDAO
    +DatabaseConnection
}